--UPDATE STATISTICS [AutoSalesSBD].[dbo].[RSMPhone] WITH FULLSCAN
--go
--UPDATE STATISTICS [AutoSalesSBD].[dbo].[SIOWarranty] WITH FULLSCAN
--go
--UPDATE STATISTICS [AutoSalesSBD].[dbo].[SIOCarLnkCar] WITH FULLSCAN
--go
UPDATE STATISTICS [AutoSalesSS].[dbo].[SSUBill] WITH FULLSCAN
go
UPDATE STATISTICS [AutoSalesSS].[dbo].[SSUCalc] WITH FULLSCAN
go
