

declare @tableDates table (
   Datet datetime)

insert into @tableDates ( 
   Datet 
)
          select dateadd(year ,-6 ,getdate())
    union select dateadd(year ,-5 ,getdate())
    union select dateadd(year ,-4 ,getdate())
    union select dateadd(year ,-3 ,getdate())
    union select dateadd(year ,-2 ,getdate())
    union select dateadd(year ,-1 ,getdate())

    union select dateadd(month ,-35 ,getdate())
    union select dateadd(month ,-26 ,getdate())
    union select dateadd(month ,-24 ,getdate())
    union select dateadd(month ,-22 ,getdate())
    union select dateadd(month ,-18 ,getdate())
    union select dateadd(month ,-17 ,getdate())
    union select dateadd(month ,-14 ,getdate())
    union select dateadd(month ,-12 ,getdate())
    union select dateadd(month ,-9 ,getdate())
    union select dateadd(month ,-8 ,getdate())
    union select dateadd(month ,-6 ,getdate())
    union select dateadd(month ,-4 ,getdate())
    union select dateadd(month ,-3 ,getdate())
    union select dateadd(month ,-1 ,getdate())
    union select dateadd(month ,-2 ,getdate())
    
    union select dateadd(day ,-135 ,getdate())
    union select dateadd(day ,-226 ,getdate())
    union select dateadd(day ,-124 ,getdate())
    union select dateadd(day ,-62 ,getdate())
    union select dateadd(day ,-88 ,getdate())
    union select dateadd(day ,-97 ,getdate())
    union select dateadd(day ,-104 ,getdate())
    union select dateadd(day ,-35 ,getdate())
    union select dateadd(day ,-26 ,getdate())
    union select dateadd(day ,-24 ,getdate())
    union select dateadd(day ,-22 ,getdate())
    union select dateadd(day ,-18 ,getdate())
    union select dateadd(day ,-17 ,getdate())
    union select dateadd(day ,-14 ,getdate())
    union select dateadd(day ,-12 ,getdate())
    union select dateadd(day ,-9 ,getdate())
    union select dateadd(day ,-8 ,getdate())
    union select dateadd(day ,-6 ,getdate())
    union select dateadd(day ,-4 ,getdate())
    union select dateadd(day ,-3 ,getdate())
    union select dateadd(day ,-1 ,getdate())
    union select dateadd(day ,-2 ,getdate())
    
    union select dateadd(hour ,-135 ,getdate())
    union select dateadd(hour ,-226 ,getdate())
    union select dateadd(hour ,-124 ,getdate())
    union select dateadd(hour ,-62 ,getdate())
    union select dateadd(hour ,-88 ,getdate())
    union select dateadd(hour ,-97 ,getdate())
    union select dateadd(hour ,-104 ,getdate())
    union select dateadd(hour ,-35 ,getdate())
    union select dateadd(hour ,-26 ,getdate())
    union select dateadd(hour ,-24 ,getdate())
    union select dateadd(hour ,-22 ,getdate())
    union select dateadd(hour ,-18 ,getdate())
    union select dateadd(hour ,-17 ,getdate())
    union select dateadd(hour ,-14 ,getdate())
    union select dateadd(hour ,-12 ,getdate())
    union select dateadd(hour ,-9 ,getdate())
    union select dateadd(hour ,-8 ,getdate())
    union select dateadd(hour ,-6 ,getdate())
    union select dateadd(hour ,-4 ,getdate())
    union select dateadd(hour ,-3 ,getdate())
    union select dateadd(hour ,-1 ,getdate())
    union select dateadd(hour ,-2 ,getdate())

    union select dateadd(minute ,-135 ,getdate())
    union select dateadd(minute ,-226 ,getdate())
    union select dateadd(minute ,-124 ,getdate())
    union select dateadd(minute ,-62 ,getdate())
    union select dateadd(minute ,-88 ,getdate())
    union select dateadd(minute ,-97 ,getdate())
    union select dateadd(minute ,-104 ,getdate())
    union select dateadd(minute ,-35 ,getdate())
    union select dateadd(minute ,-26 ,getdate())
    union select dateadd(minute ,-24 ,getdate())
    union select dateadd(minute ,-22 ,getdate())
    union select dateadd(minute ,-18 ,getdate())
    union select dateadd(minute ,-17 ,getdate())
    union select dateadd(minute ,-14 ,getdate())
    union select dateadd(minute ,-12 ,getdate())
    union select dateadd(minute ,-9 ,getdate())
    union select dateadd(minute ,-8 ,getdate())
    union select dateadd(minute ,-6 ,getdate())
    union select dateadd(minute ,-4 ,getdate())
    union select dateadd(minute ,-3 ,getdate())
    union select dateadd(minute ,-1 ,getdate())
    union select dateadd(minute ,-2 ,getdate())
    union select dateadd(second ,-28 ,getdate())
    union select dateadd(second ,-15 ,getdate())
    union select getdate()


  select
       fn.datetime_to_text_ForUser(t.Datet)
    from @tableDates as t